version: '3.9'

services:
  db:
    image: postgres:15
    container_name: students_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: students_server
    depends_on:
      - db
    ports:
      - "18080:18080"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: students_db

volumes:
  db_data:
